files:
  api-single.mustache:
    folder: api
    destinationFilename: api-single.py
    templateType: SupportingFiles
api-test-single.mustache:
    folder: api
    destinationFilename: api-test.py
    templateType: SupportingFiles
